*******************************************************************************;
* US Life Table 1984                                                           ;
  %MACRO USLIFE(TABLE='SEXRACE', OUT=USLIFE, TIME=TIME, SALL=SALL,
                CHALL=CHALL, HALL=HALL, MED=0, MEDF=0, NF=0, MEDM=0,
                NM=0, MEDW=0, NW=0, MEDO=0, NO=0, MEDWF=0, NWF=0,
                MEDWM=0, NWM=0, MEDOF=0, NOF=0, MEDOM=0, NOM=0, MAX=100,
                SCALE='YEARS', NINC=999.9, PLOT=0, PRINT=0, SW=SW,
                SO=SO, SF=SF, SM=SM, SWF=SWF, SWM=SWM, SOF=SOF, SOM=SOM,
                HW=HW, HO=HO, HF=HF, HM=HM, HWF=HWF, HWM=HWM, HOF=HOF,
                HOM=HOM);
*______________________________________________________________________________;
*                                                                              ;
* DEFINITIONS OF CALLING ARGUMENTS:            DEFAULT:                        ;
*                                                                              ;
*   TABLE    = Type of life table:               'SEXRACE'                     ;
*                'OVERALL' = Overall table                                     ;
*                'SEX'     = Table by gender                                   ;
*                'RACE'    = Table by race                                     ;
*                'SEXRACE' = Table by sex and race                             ;
*   IN       = Input data set name               last SAS data set             ;
*   OUT      = Output data set name              USLIFE                        ;
*                                                                              ;
* Names of the output variables:                                               ;
*   TIME     = Time axis variable name           TIME                          ;
*                (values in the units of SCALE)                                ;
*   SALL     = Survivorship function             SALL                          ;
*   CHALL    = Cumulative hazard function        CHALL                         ;
*   HALL     = Hazard function scaled in the     HALL                          ;
*                units of SCALE                                                ;
* NOTE:  Individual survivorship and hazard pieces are available on            ;
*        the output data set as well.                                          ;
*                                                                              ;
* For overall life table (TABLE='OVERALL'):                                    ;
*   MED      = Median age (years): all           0 years                       ;
*     NOTE:  All median ages are given in years.                               ;
*            The input can read 23/365.2425, or                                ;
*            9/12, or 42 for neonates, infants,                                ;
*            or older people.                                                  ;
*                                                                              ;
* For life table according to gender (TABLE='SEX'):                            ;
*   MEDF     = Median age (years): females       0 years                       ;
*   NF       = Number: females                   0                             ;
*   MEDM     = Median age (years): males         0 years                       ;
*   NM       = Number: males                     0                             ;
*                                                                              ;
* For life table according to ethnicity (TABLE='RACE'):                        ;
*   MEDW     = Median age (years): white race    0 years                       ;
*   NW       = Number: white race                0                             ;
*   MEDO     = Median age (years): other race    0 years                       ;
*   NO       = Number: other race                0                             ;
*                                                                              ;
* For life table according to gender and ethnicity (TABLE='SEXRACE'):          ;
*   MEDWF    = Median age (years): white females 0 years                       ;
*   NWF      = Number: white females             0                             ;
*   MEDWM    = Median age (years): white males   0 years                       ;
*   NWM      = Number: white males               0                             ;
*   MEDOF    = Median age (years): other females 0 years                       ;
*   NOF      = Number: other race females        0                             ;
*   MEDOM    = Median age (years): other males   0 years                       ;
*   NOM      = Number: other race males          0                             ;
*                                                                              ;
* Time scale of the life table (default is years):                             ;
* NOTE:  MAX on input and TIME and HALL on output is scaled by SCALE           ;
*   MAX      = Maximum followup time             100                           ;
*   SCALE    = Time scale of input and output:   'YEARS'                       ;
*                'DAYS'   = Scale in days                                      ;
*                'MONTHS' = Scale in months                                    ;
*                'YEARS'  = Scale in years                                     ;
*   NINC     = Number of increments              999.9 (for 1001 points)       ;
*                                                                              ;
* Plotting and printing options:                                               ;
*   PLOT     = Plot survival and hazard          0 (1 to plot)                 ;
*   PRINT    = Print survival and hazard         0 (1 to print)                ;
*______________________________________________________________________________;
*                                                                              ;
  LIBNAME USLIFE84 '/studies/cardiac/general/uslife/table84/estimates';
  DATA &OUT;
  &SALL=.; &CHALL=.; &HALL=.;
  INC=&MAX/&NINC;
* Determine scaling (NOTE:  Hazard will be scaled in units of SCALE)           ;
  SCALEF=.;
  %IF &SCALE='YEARS' %THEN %DO;; SCALEF=1; %GOTO CALC; %END;;
  %IF &SCALE='MONTHS' %THEN %DO;; SCALEF=1/12; %GOTO CALC; %END;;
  %IF &SCALE='DAYS' %THEN %DO;; SCALEF=1/365.2425; %GOTO CALC; %END;;
* We should not be here, so get out                                            ;
  %GOTO PRINT;
  %CALC:;
* Generate time axis in units of SCALE                                         ;
  DO &TIME=0 TO &MAX BY INC, &MAX;
    YEARS=&TIME*SCALEF;
    OUTPUT;
  END;
*______________________________________________________________________________;
*                                                                              ;
* Overall Life Table                                                           ;
  %IF &TABLE='OVERALL' %THEN %DO;;
    DATA &OUT; SET &OUT;
    AGE_YR=&MED + YEARS;
*******************************************************************************;
* Get estimates                                                                ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICALL OUT=&OUT NOCL;
         TIME AGE_YR;)
*******************************************************************************;
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SALL=_SURVIV/SURV_MED; &HALL=_HAZARD*SCALEF; &CHALL=-LOG(&SALL);
*******************************************************************************;
* Plot result                                                                  ;
    %IF &PLOT=1 %THEN %DO;;
      PROC PLOT; PLOT &SALL*&TIME='*' &CHALL*&TIME='*' &HALL*&TIME='*';
    %END;
    %GOTO PRINT;
  %END;
*______________________________________________________________________________;
*                                                                              ;
* Life Table by gender                                                         ;
  %IF &TABLE='SEX' %THEN %DO;;
    DATA &OUT; SET &OUT;
*******************************************************************************;
* Get estimates for females                                                    ;
    AGE_YR=&MEDF + YEARS;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICF OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SF=_SURVIV/SURV_MED; &HF=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DF=_SURVIV*&HF; _SF=_SURVIV;
* Set up for males                                                             ;
    AGE_YR=&MEDM + YEARS;
    KEEP &TIME SCALEF &SF &HF DF _SF AGE_YR;
*******************************************************************************;
* Get estimates for males                                                      ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICM OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SM=_SURVIV/SURV_MED; &HM=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DM=_SURVIV*&HM; _SM=_SURVIV;
*******************************************************************************;
* Now put these all together, weighted by the number in each category          ;
    NALL=&NF + &NM;
* Since densities and probabilities add (and must be confined to the           ;
* interval from 0 to 1), simply find the average weighted survivorship         ;
* and death density functions.                                                 ;
    &SALL=(&NF*&SF + &NM*&SM)/NALL;
*   DALL=(&NF*DF + &NM*DM)/NALL;
    DALL=0; IF &NF>0 THEN DALL=DALL+&NF*DF;
            IF &NM>0 THEN DALL=DALL+&NM*DM;
* To determine the hazard, use the relation hazard=density/survival.           ;
    S_DALL=(&NF*_SF + &NM*_SM)/NALL; &HALL=(DALL/NALL)/S_DALL;
* Cumulative hazard function                                                   ;
    &CHALL=-LOG(&SALL);
    KEEP &TIME &SF &HF &SM &HM &SALL &HALL &CHALL;
*******************************************************************************;
* Plot result                                                                  ;
    %IF &PLOT=1 %THEN %DO;;
      PROC PLOT; PLOT &SALL*&TIME='*' &SF*&TIME='F' &SM*&TIME='M'/OVERLAY;
                 PLOT &HALL*&TIME='*' &HF*&TIME='F' &HM*&TIME='M'/OVERLAY;
    %END;
    %GOTO PRINT;
  %END;
*______________________________________________________________________________;
*                                                                              ;
* Life Table by ethnicity                                                      ;
  %IF &TABLE='RACE' %THEN %DO;;
    DATA &OUT; SET &OUT;
*******************************************************************************;
* Get estimates for whites                                                     ;
    AGE_YR=&MEDW + YEARS;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICW OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SW=_SURVIV/SURV_MED; &HW=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DW=_SURVIV*&HW; _SW=_SURVIV;
* Set up for other races                                                       ;
    AGE_YR=&MEDO + YEARS;
    KEEP &TIME SCALEF &SW &HW DW _SW AGE_YR;
*******************************************************************************;
* Get estimates for other races                                                ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICO OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SO=_SURVIV/SURV_MED; &HO=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DO=_SURVIV*&HO; _SO=_SURVIV;
*******************************************************************************;
* Now put these all together, weighted by the number in each category          ;
    NALL=&NW + &NO;
* Since densities and probabilities add (and must be confined to the           ;
* interval from 0 to 1), simply find the average weighted survivorship         ;
* and death density functions.                                                 ;
    &SALL=(&NW*&SW + &NO*&SO)/NALL;
*   DALL=(&NW*DW + &NO*DO)/NALL;
    DALL=0; IF &NW>0 THEN DALL=DALL+&NW*DW;
            IF &NO>0 THEN DALL=DALL+&NO*DO;
* To determine the hazard, use the relation hazard=density/survival.           ;
    S_DALL=(&NW*_SW + &NO*_SO)/NALL; &HALL=(DALL/NALL)/S_DALL;
* Cumulative hazard function                                                   ;
    &CHALL=-LOG(&SALL);
    KEEP &TIME &SW &HW &SO &HO &SALL &HALL &CHALL;
*******************************************************************************;
* Plot result                                                                  ;
    %IF &PLOT=1 %THEN %DO;;
      PROC PLOT; PLOT &SALL*&TIME='*' &SW*&TIME='W' &SO*&TIME='O'/OVERLAY;
                 PLOT &HALL*&TIME='*' &HW*&TIME='W' &HO*&TIME='O'/OVERLAY;
    %END;
    %GOTO PRINT;
  %END;
*______________________________________________________________________________;
*                                                                              ;
* Life Table by gender and ethnicity                                           ;
  %IF &TABLE='SEXRACE' %THEN %DO;;
    DATA &OUT; SET &OUT;
*******************************************************************************;
* Get estimates for white males                                                ;
    AGE_YR=&MEDWM + YEARS;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICWM OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SWM=_SURVIV/SURV_MED; &HWM=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DWM=_SURVIV*&HWM; _SWM=_SURVIV;
* Set up for other males                                                       ;
    AGE_YR=&MEDOM + YEARS;
    KEEP &TIME SCALEF &SWM &HWM DWM _SWM AGE_YR YEARS;
*******************************************************************************;
* Get estimates for other males                                                ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICOM OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SOM=_SURVIV/SURV_MED; &HOM=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DOM=_SURVIV*&HOM; _SOM=_SURVIV;
* Set up for white females                                                     ;
    AGE_YR=&MEDWF + YEARS;
    KEEP &TIME SCALEF &SWM &HWM DWM _SWM &SOM &HOM DOM _SOM AGE_YR YEARS;
*******************************************************************************;
* Get estimates for white females                                              ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICWF OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SWF=_SURVIV/SURV_MED; &HWF=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DWF=_SURVIV*&HWF; _SWF=_SURVIV;
* Set up for other females                                                     ;
    AGE_YR=&MEDOF + YEARS;
    KEEP &TIME SCALEF &SWM &HWM DWM _SWM &SOM &HOM DOM _SOM &SWF &HWF DWF _SWF
         AGE_YR YEARS;
*******************************************************************************;
* Get estimates for other females                                              ;
    %HAZPRED(
    PROC HAZPRED DATA=&OUT INHAZ=USLIFE84.HZICOF OUT=&OUT NOCL;
         TIME AGE_YR;)
* Normalize to the median age                                                  ;
    DATA &OUT; SET &OUT;
    RETAIN SURV_MED 0;
    IF _N_=1 THEN SURV_MED=_SURVIV;
    &SOF=_SURVIV/SURV_MED; &HOF=_HAZARD*SCALEF;
* Calculate density function, and save survivorship function for               ;
* eventual combining of the data.                                              ;
    DOF=_SURVIV*&HOF; _SOF=_SURVIV;
*******************************************************************************;
* Now put these all together, weighted by the number in each category          ;
    NALL=&NWM + &NOM + &NWF + &NOF;
* Since densities and probabilities add (and must be confined to the           ;
* interval from 0 to 1), simply find the average weighted survivorship         ;
* and death density functions.                                                 ;
    &SALL=(&NWM*&SWM + &NOM*&SOM + &NWF*&SWF + &NOF*&SOF)/NALL;
*    DALL=(&NWM*DWM + &NOM*DOM + &NWF*DWF + &NOF*DOF)/NALL;
     DALL=0; IF &NWM>0 THEN DALL=DALL+&NWM*DWM;
             IF &NOM>0 THEN DALL=DALL+&NOM*DOM;
             IF &NWF>0 THEN DALL=DALL+&NWF*DWF;
             IF &NOF>0 THEN DALL=DALL+&NOF*DOF;
* To determine the hazard, use the relation hazard=density/survival.           ;
    S_DALL=(&NWM*_SWM + &NOM*_SOM + &NWF*_SWF + &NOF*_SOF)/NALL;
    &HALL=(DALL/NALL)/S_DALL;
* Cumulative hazard function                                                   ;
    &CHALL=-LOG(&SALL);
    KEEP &TIME &SWF &SWM &HWF &HWM &SOF &SOM &HOF &HOM &SALL &HALL
         &CHALL;
*******************************************************************************;
* Plot result                                                                  ;
    %IF &PLOT=1 %THEN %DO;;
      PROC PLOT;
           PLOT &SALL*&TIME='*' &SWM*&TIME='1' &SOM*&TIME='2'
                &SWF*&TIME='3' &SOF*&TIME='4'/OVERLAY;
           PLOT &HALL*&TIME='*' &HWM*&TIME='1' &HOM*&TIME='2'
                &HWF*&TIME='3' &HOF*&TIME='4'/OVERLAY;
    %END;
    %GOTO PRINT;
  %END;
*______________________________________________________________________________;
*                                                                              ;
* Print result if desired                                                      ;
  %PRINT:;
  %IF &PRINT=1 %THEN %DO;;
    PROC PRINT DATA=&OUT; VAR &TIME &SALL &CHALL &HALL;
  %END;
*******************************************************************************;
  %MEND USLIFE;
*******************************************************************************;
